[project]
name = "mcp-playground"
version = "0.1.0"
description = "A playground for experimenting with MCP and language models."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.75.0",
    "fastmcp>=2.13.1",
    "mcp[cli]>=1.22.0",
    "python-dotenv>=1.2.1",
]
